### ISSUE TITLE
rune of sarlacc does not remove drops at edge but still kill mobs and creates xp.

### ISSUE THREAD

**Issue by matyklug18** [Xilef11/runesofwizardry-classics#16]

**Comment by Xilef11** [comment]
The rune of Sarlacc destroys any mobs and items dropped on it. If a mob is killed at the edge and its drops fall outside the rune, they won't be destroyed. 

Strictly speaking it's not a bug, but I see how this could be abused to get both drops and double XP, so I'll look into fixing it. However, it may take a while since I don't have much time right now.
